Setting intial theme using user preference
codesandbox/sandpack pull request #19
Opened 2021-03-08 06:20 UTC by JayaKrishnaNamburu

fixes #6

2021-03-09 20:56 UTC, alexnm requested changes

2021-03-09 20:56 UTC, alexnm commented on sandpack-react/src/contexts/theme-context.tsx
> +    themeObj = createThemeObject(props.theme);
if you make the changes above, you can keep the injectThemeStyleSheet behind the props.theme check

2021-03-10 08:03 UTC, JayaKrishnaNamburu commented
sure alex, wll be making those changes 👍

2021-03-10 17:47 UTC, alexnm requested changes
Looks great, thanks for the effort! Just a small change request and we're good to go

2021-03-10 17:47 UTC, alexnm commented on sandpack-react/src/themes/index.ts
> +    const theme = getDarkModePreference()
here you can also assign the id to `codesandbox-light` or `codesandbox-dark` so you don't generate a new hash for the theme. `auto` will still set a standard theme, the hash function is created for custom themes. Also, move this after the `if(inputTheme === undefined)`

2021-03-11 09:16 UTC, alexnm approved these changes

2021-03-11 09:17 UTC, merged