[Feature request]: Add `initialCursor` to code editor when setting the active file
codesandbox/sandpack pull request #569
Opened 2022-09-06 19:46 UTC by mattphillips

## What kind of change does this pull request introduce?

This PR closes https://github.com/codesandbox/sandpack/issues/558

## What is the current behavior?

Currently sandpack has a `setActiveFile` function that can only open the file without putting the cursor at a given position.

## What is the new behavior?

This PR adds an optional `cursor` (line / column numbers) to the `setActiveFile` function. If a cursor position is set as part of this function then the `CodeMirror` state has a selection at the given cursor and will scroll it into view and focus the editor.

This PR also introduces a change to `SandpackTests`. I've rewritten the `FormattedErrors` component to use JSX instead of relying of string manipulation and dangerously rendering the string. The reason to do this is so that we can safely attach an `onClick` to the failing matcher error which will open the test file at the correct position to fix the matcher.

## What steps did you take to test this? This is required before we can merge, make sure to test the flow you've updated.

See attached demo of the cursor change in action using `SandpackTests` errors.

https://user-images.githubusercontent.com/5610087/188724977-099ca5d5-b5cc-43a0-b45d-9cd9420a6968.mov

## Checklist

- [ ] Documentation;
- [x] Storybook (if applicable);
- [ ] Tests;
- [ ] Ready to be merged;

## Todo

- I'm going to hold off updating the docs until @danilowoz has had a chance to look this over and he's happy with everything I'll get the docs updated too.

2022-09-29 10:08 UTC, mattphillips commented
Hey @danilowoz 👋 have you had a chance to look at this? Anything you need me to change or do?

2022-10-04 12:50 UTC, danilowoz requested changes
I just left some comments, but so far it looks good to me

2022-10-04 12:50 UTC, danilowoz commented on sandpack-react/src/components/CodeEditor/CodeMirror.tsx
> +        let editorSelection: EditorSelection;
Good stuff!

2022-10-04 12:50 UTC, danilowoz commented on sandpack-react/src/components/Tests/FormattedError.tsx
> +const makeMargin = (length: number): string =>
Could you elaborate on what has changed from this point?

2022-10-04 12:50 UTC, danilowoz commented on sandpack-react/src/types.ts
> +export interface Cursor {
Maybe CodePosition, CursorPosition, or FilePosition?

2022-10-04 12:50 UTC, danilowoz commented on sandpack-react/src/components/Tests/utils.ts
> +export class ReactStringReplacer {
Could you leave a comment here explaining the reason for using this implementation and what it does?

2022-10-04 12:50 UTC, danilowoz commented on sandpack-react/src/contexts/sandpackContext.tsx
> +    this.setState({ activeFile, initialCursor });
Shouldn't we clean the `initialCursor` after opening the file? I was wondering if it might affect the next file and use a stale value.

2023-04-06 21:00 UTC, danilowoz commented
Hey, I'm going to close this, as it has been a while. Feel free to reopen it anytime 
Thanks!

2023-04-06 21:00 UTC, closed without merging